// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtauguvmkkyudktehoel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0YXVndXZta2t5dWRrdGVob2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNjc1MTIsImV4cCI6MjA4NDg0MzUxMn0._UlxOleWXQP9-GezxzSw8sIfV_HNECQKVmw9Uyfruik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});